export const ADD_ERROR = 'ADD_ERROR';
export const REMOVE_ERROR = 'REMOVE_ERROR';
export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const LOAD_POSTS = 'LOAD_POSTS';
export const UPDATE_POST = 'UPDATE_POST';
export const REMOVE_POST = 'REMOVE_POST';
export const GET_FRIEND = 'GET_FRIEND';
export const DELETE_FRIEND_FROM_STATE = 'DELETE_FRIEND_FROM_STATE';